### PR TITLE
Adding guard to header file to allow include in multiple files

### PR DESCRIPTION
**Pull request by AmmarKothari**
Adds a guard to the header file to allow for include into multiple files in the same executable.

### CODE REVIEW

**Comment by morsisko** [comment]
Thanks

**Comment by AmmarKothari** [comment]
Would it be possible to create a new release for this version so I can grab it through the package manager?

**Comment by morsisko** [comment]
I already added it, should be possible to grab through the package manager soon

**Comment by AmmarKothari** [comment]
Thanks!

**Pull request merged**
